# Generated by Django 3.1.7 on 2021-03-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0005_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='type',
        ),
    ]
