# Generated by Django 3.1.7 on 2021-03-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0006_remove_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
