# Generated by Django 3.1.7 on 2021-03-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0011_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
