# Generated by Django 3.1.7 on 2021-03-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0013_auto_20210330_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
