# Generated by Django 3.1.7 on 2021-03-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0014_auto_20210330_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
