# Generated by Django 3.1.7 on 2021-03-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0015_auto_20210331_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
