# Generated by Django 3.1.7 on 2021-03-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0016_auto_20210331_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
