# Generated by Django 3.1.7 on 2021-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0018_auto_20210401_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
