# Generated by Django 3.1.7 on 2021-04-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0019_auto_20210402_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='discount',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
