# Generated by Django 3.1.7 on 2021-04-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0021_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='discount',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
